"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

# : Flavor {{{

[flavor]
dark  = ""
light = ""

# : }}}

# : Manager {{{

[manager]
cwd = { fg = "cyan" }

# Hovered
hovered         = { reversed = true }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "yellow", bold = true, italic = true, underline = true }
find_position = { fg = "magenta", bg = "reset", bold = true, italic = true }

# Marker
marker_copied   = { fg = "lightgreen",  bg = "lightgreen" }
marker_cut      = { fg = "lightred",    bg = "lightred" }
marker_marked   = { fg = "lightcyan",   bg = "lightcyan" }
marker_selected = { fg = "lightyellow", bg = "lightyellow" }

# Tab
tab_active   = { reversed = true }
tab_inactive = {}
tab_width    = 1

# Count
count_copied   = { fg = "white", bg = "green" }
count_cut      = { fg = "white", bg = "red" }
count_selected = { fg = "white", bg = "yellow" }

# Border
border_style  = { fg = "gray" }

# Highlighting
syntect_theme = ""

# : }}}


# : Mode {{{

[mode]

# normal_main = { fg = "black", bg = "blue", bold = true }
# normal_alt  = { fg = "blue", bg = "black" }

# Select mode
# select_main = { bg = "red", bold = true }
# select_alt  = { fg = "red", bg = "gray" }

# Unset mode
# unset_main = { bg = "red", bold = true }
# unset_alt  = { fg = "red", bg = "gray" }

normal_main = { fg = "reset", bg = "reset", reversed = true, bold = true }
normal_alt  = { fg = "reset", bg = "reset", reversed = true }
select_main = { fg = "red", bg = "reset", reversed = true, bold = true }
select_alt  = { fg = "red", bg = "reset", reversed = true }
unset_main = { fg = "red", bg = "reset", reversed = true, bold = true }
unset_alt  = { fg = "red", bg = "reset", reversed = true }

# : }}}


# : Status bar {{{

[status]
# separator_open  = ""
# separator_close = ""
separator_open  = " "
separator_close = " "

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "blue", bg = "black" }
progress_error  = { fg = "red", bg = "black" }

# Permissions
perm_sep   = { fg = "darkgray" }
perm_type  = { fg = "green" }
perm_read  = { fg = "yellow" }
perm_write = { fg = "red" }
perm_exec  = { fg = "cyan" }

# : }}}


# : Pick {{{

[pick]
border   = { fg = "blue" }
active   = { fg = "magenta", bold = true }
inactive = {}

# : }}}


# : Input {{{

[input]
border   = { fg = "blue" }
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


# : Confirm {{{

[confirm]
border     = { fg = "blue" }
title      = { fg = "blue" }
content    = {}
list       = {}
btn_yes    = { reversed = true }
btn_no     = {}
btn_labels = [ "  [Y]es  ", "  (N)o  " ]

# : }}}


# : Completion {{{

[completion]
border   = { fg = "blue" }
active   = { reversed = true }
inactive = {}

# : }}}


# : Tasks {{{

[tasks]
border  = { fg = "blue" }
title   = {}
hovered = { fg = "magenta", underline = true }

# : }}}


# : Which {{{

[which]
cols            = 3
mask            = { bg = "black" }
cand            = { fg = "lightcyan" }
rest            = { fg = "darkgray" }
desc            = { fg = "lightmagenta" }
separator       = "  "
separator_style = { fg = "darkgray" }

# : }}}


# : Help {{{

[help]
on      = { fg = "cyan" }
run     = { fg = "magenta" }
desc    = {}
hovered = { reversed = true, bold = true }
footer  = { fg = "black", bg = "white" }

# : }}}


# : Notify {{{

[notify]
title_info  = { fg = "green" }
title_warn  = { fg = "yellow" }
title_error = { fg = "red" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "yellow" },

	# Media
	{ mime = "{audio,video}/*", fg = "magenta" },

	# Archives
	{ mime = "application/{,g}zip", fg = "red" },
	{ mime = "application/{tar,bzip*,7z*,xz,rar}", fg = "red" },

	# Documents
	{ mime = "application/{pdf,doc,rtf}", fg = "cyan" },

	# Empty files
	# { mime = "inode/empty", fg = "red" },

	# Special files
	{ name = "*", is = "orphan", bg = "red" },
	{ name = "*", is = "exec"  , fg = "green" },

	# Dummy files
	{ name = "*", is = "dummy", bg = "red" },
	{ name = "*/", is = "dummy", bg = "red" },

	# Fallback
	# { name = "*", fg = "white" },
	{ name = "*/", fg = "blue" }
]

# : }}}

